title: Luca Benfenati 
url: "https://lucabnf.github.io"
remote_theme: ankitsultana/researcher@gem

markdown: kramdown
#ins_logo: "./bits-logo.png"
plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

tracking_id: #

footer: yes
footer_url: "https://github.com/lucabnf"

sass:
    style: compressed
    sass_dir: _sass

nav:
#  - name: "About"
#    link: "/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
 - name: "Interests"
   link: "interests"